project:
  type: website
  output-dir: ../docs

website:
  title: "AI job market impact"
  description: "Generative AI and tech hiring, 2019-2026"
  search: true
  navbar: {}
  sidebar:
    style: floating
    contents:
      - section: "Overview"
        contents:
          - text: "Home"
            href: index.qmd
          - introduction.qmd
          - dataprep_eda.qmd
      - section: "Unsupervised"
        contents:
          - clustering.qmd
          - pca.qmd
      - section: "Supervised"
        contents:
          - naivebayes.qmd
          - dectrees.qmd
          - svm.qmd
          - regression.qmd
          - nn.qmd
      - section: "Closing"
        contents:
          - conclusions.qmd
          - about.qmd

format:
  html:
    theme:
      light: [cosmo, styles.scss]
      dark: [darkly, styles-dark.scss]
    toc: true
    toc-location: right
    toc-depth: 3
