project:
  type: website
  output-dir: ../docs

website:
  title: "AI & the Job Market"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Introduction"
        href: introduction.qmd
      - text: "DataPrep_EDA"
        href: dataprep_eda.qmd
      - text: "Methods"
        menu:
          - text: "Clustering"
            href: clustering.qmd
          - text: "PCA"
            href: pca.qmd
          - text: "NaiveBayes"
            href: naivebayes.qmd
          - text: "DecTrees"
            href: dectrees.qmd
          - text: "SVMs"
            href: svm.qmd
          - text: "Regression"
            href: regression.qmd
          - text: "NN"
            href: nn.qmd
      - text: "Conclusions"
        href: conclusions.qmd
      - text: "About Me"
        href: about.qmd

format:
  html:
    theme:
      - cosmo
      - styles.css
    toc: true
    toc-location: right
