project:
  type: website
  output-dir: ../docs

website:
  title: "AI job market impact"
  description: "Generative AI and tech hiring"
  search: true
  navbar:
    collapse-below: xl
    left:
      - href: index.qmd
        text: "Home"
      - href: introduction.qmd
        text: "Introduction"
      - href: dataprep_eda.qmd
        text: "Data Prep & EDA"
      - text: "Unsupervised"
        menu:
          - href: clustering.qmd
            text: "Clustering"
          - href: pca.qmd
            text: "PCA"
      - text: "Supervised"
        menu:
          - href: naivebayes.qmd
            text: "Naive Bayes"
          - href: dectrees.qmd
            text: "Decision Trees"
          - href: svm.qmd
            text: "SVMs"
          - href: regression.qmd
            text: "Regression"
          - href: nn.qmd
            text: "Neural Networks"
      - href: conclusions.qmd
        text: "Conclusions"
      - href: about.qmd
        text: "About Me"
    right:
      - icon: github
        href: https://github.com/RahulHipparkar/ai-job-market-impact

format:
  html:
    theme:
      light: [cosmo, styles.scss]
      dark: [darkly, styles-dark.scss]
    toc: false
    page-layout: full
    code-overflow: wrap
